In [1]:
!pip install joblib


     ------------------------------------ 302.2/302.2 kB 548.8 kB/s eta 0:00:00


In [33]:
import os
import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [79]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int =None):
        self.weights=np.random.randn(3)*1e-4 ## to make weight smaller
        self.eta=eta
        self.epochs=epochs
        
    def _z_outcome(self,X,weights):
        return np.dot(X,weights)
    
    def Activation_function(self,z):
        return np.where(z>0,1,0)
        
    def fit(self,X,y):
        
        self.X=X
        self.y=y
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))] ## This will Create metrix same as weight Updation metrix in notebook
        print(f"X with Bias is \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            z=self._z_outcome(X_with_bias,self.weights)
            y_hat=self.Activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            error=self.y-y_hat
            print(f"Error is \n{error}")
            
            self.weights=self.weights + self.eta * np.dot(X_with_bias.T,error)
            print(f"Updated Weights after epochs: {epoch+1}/{self.epochs} are \n{self.weights}")
        
    def predict(self,X):
            X_with_bias=np.c_[X,-np.ones((len(X),1))]
            z=self._z_outcome(X_with_bias,self.weights)
            y_hat=self.Activation_function(z)
            return y_hat

In [80]:
def Prepare_data(dataframe,target_value="y"):
    X=dataframe.drop("y",axis=1)
    y=dataframe[target_value]
    return X,y

In [81]:
OR={
    "X1":[1,0,0,1],
    "X2":[0,1,0,1],
    "y":[1,1,0,1]  
}
df=pd.DataFrame(OR)

In [82]:
X,y=Prepare_data(df)

In [83]:
ETA=0.01
EPOCHS=10
OR_prediction=Perceptron(eta=ETA,epochs=EPOCHS)
OR_prediction.fit(X,y)

X with Bias is 
[[ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 0.  0. -1.]
 [ 1.  1. -1.]]
predicted value after forward pass: 
[0 1 0 1]
Error is 
0    1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights after epochs: 1/10 are 
[ 0.00993202  0.00012612 -0.00994336]
predicted value after forward pass: 
[1 1 1 1]
Error is 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
Updated Weights after epochs: 2/10 are 
[9.93202218e-03 1.26117273e-04 5.66384737e-05]
predicted value after forward pass: 
[1 1 0 1]
Error is 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights after epochs: 3/10 are 
[9.93202218e-03 1.26117273e-04 5.66384737e-05]
predicted value after forward pass: 
[1 1 0 1]
Error is 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights after epochs: 4/10 are 
[9.93202218e-03 1.26117273e-04 5.66384737e-05]
predicted value after forward pass: 
[1 1 0 1]
Error is 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights after epochs: 5/10 are 
[9.932022

In [89]:
or_pred=OR_prediction.predict(X=[[1,1]])

In [90]:
or_pred

array([1])