In [1]:
!pip install joblib


     ------------------------------------ 302.2/302.2 kB 548.8 kB/s eta 0:00:00


In [2]:
import os
import joblib
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("fivethirtyeight")

In [16]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int =None):
        self.weights=np.random.randn(3)*1e-4 ## to make weight smaller
        self.eta=eta
        self.epochs=epochs
        
    def fit(self,X,y):
        self.X=X
        self.y=y
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))] ## This will Create metrix same as weight Updation metrix in notebook
        print(f"X with Bias is \n{X_with_bias}")

In [17]:
perceptron=Perceptron(eta=0.01,epochs=10)

In [18]:
perceptron.eta

0.01

In [19]:
perceptron.epochs

10

In [20]:
X=np.ones((4,2))

In [21]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
y=np.ones((4,1))

In [26]:
perceptron.fit(X,y)

X with Bias is 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
